### ISSUE TITLE
Extend to support plugins

### ISSUE THREAD

**Issue by rottmann** [KingYes/wordpress-aryo-activity-log#71]
Great plugin!
With a little work I think this plugin could be a base plugin / alternative for many developer that hack their own notification and logging system.

It would be really nice if you can extend your api / hooks to allow plugins to use the logger.

I create a plugin that e.g. run cron-jobs and i want to save different custom events and enable to select them for notification. At the moment that is not possible.

The notification need some attributes like: notify when this event occured 10 times, or notfiy once per day / week / month....

`Export` is missing in `classes/class-aal-notifications.php::get_object_types`

**Comment by KingYes** [comment]
Fixed. Sorry about that.
