### ISSUE TITLE
ManageWP requests are logged with wrong username

### ISSUE THREAD

**Issue by varvas** [KingYes/wordpress-aryo-activity-log#72]
I'm using ManageWP to manage my sites and I just discovered that all requests from that system are logged with first admin account available. At first it was an account with ID 1, then I deleted it and now it's logging with user ID 2.

**Comment by KingYes** [comment]
I don't understand what you want to do. Can you explain yourself?

**Comment by varvas** [comment]
Well, for example, when I trigger a plugin update from the ManageWP portal, this action is logged with first admin username found.

**Comment by KingYes** [comment]
The first username (ID:1) is not found in your system anymore?

**Comment by varvas** [comment]
No it isn't.
I think, what happens is, that one of the two plugins (yours or the ManageWP Worker) is querying for all admin users, ordering them by id and finally selecting the first one.

**Comment by KingYes** [comment]
I don't know what that's bug. sorry :|

**Comment by varvas** [comment]
OK. I'll try to work around it somehow

**Comment by KingYes** [comment]
Please let's me know if you fix this.
