### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mathetos** [KingYes/wordpress-aryo-activity-log#77]
Would love to be able to SORT by the IP Address column. This would enable the following scenario:

1) Filter by "wrong_password"
2) Sort by IP Address
3) See who the worst offenders of the wrong_password are so we can add them to a banned IP list.

Thanks!

**Comment by KingYes** [comment]
1) Fixed in #71
2) Work about that
3) What you mean? Do you need IP adress list?

**Comment by mathetos** [comment]
Oh, I just mean if the SORT by IP address exists in that column, then we'd see that for example: 12.34.567.8 is listed 200 times, then we know that's just a BOT and we can add them to our list. No need for you to add another feature, just saying what we could do once the SORT is available.

**Comment by KingYes** [comment]
Done :)

**Comment by mathetos** [comment]
Awesome. Looking forward to it!

**Comment by KingYes** [comment]
Released

**Comment by damelco** [comment]
was the added to the "Feature List" or added to the "Plugin" (actually implemented)

if it was added to the "Plugin" ,,, and was then functional ... it is broken non-functional.

although the Column-Label is clickable and doing do changes the displayed order ... it definitely is NOT sorted by IP?!

regards,

-DJ
