### ISSUE TITLE
Posts are deleted by Guest

### ISSUE THREAD

**Issue by sunfffd** [KingYes/wordpress-aryo-activity-log#81]
Hi,

Not sure why but it seems the delete post action are recorded as Guest
![unnamed](https://cloud.githubusercontent.com/assets/1101122/10505255/183a76b2-733e-11e5-8919-85e917b3c982.gif)

**Comment by KingYes** [comment]
What you doing and you see that?

**Comment by sunfffd** [comment]
Hello,

I tried normal deletion by admin user and it's displaying the user name normally.

From some of the logs the Guest IP is 127.0.0.1, so it's localhost.
I think this is the automatic trash deletion triggered by WordPress, worth noting though.
Posts in trash are cleared in 30 days by default.
http://codex.wordpress.org/Trash_status

Can you confirm?

**Comment by KingYes** [comment]
Oh.. If it's automatic trash deletion.. it's get author name Guest.

**Comment by sunfffd** [comment]
Thanks, 
From the screenshot you can also see some logout action done by guest, I guess those are from crawlers or bots right?

**Comment by KingYes** [comment]
I think so :)
