### ISSUE TITLE
2.2.8 errors: Trying to get property of non-object

### ISSUE THREAD

**Issue by odie2** [KingYes/wordpress-aryo-activity-log#83]
Hi,

My `debug.log` file is spammed from yesterday's update with following:

```
[23-Jan-2016 20:03:19 UTC] PHP Notice:  Trying to get property of non-object in /home/[...]/wordpress/wp-content/plugins/aryo-activity-log/classes/freemius/includes/class-fs-api.php on line 161

[23-Jan-2016 20:03:19 UTC] PHP Notice:  Trying to get property of non-object in /home/[...]/wordpress/wp-content/plugins/aryo-activity-log/classes/freemius/includes/class-fs-api.php on line 178
```

And
```
[23-Jan-2016 20:10:35 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/[...]/wordpress/wp-content/plugins/aryo-activity-log/classes/freemius/includes/class-fs-api.php:161) in /home/[...]/wordpress/wp-content/themes/zschocianow/header.php on line 62
```
I use in header.php only `setcookie()` before and after line 62. There were no such error before.

Greetings

**Comment by vovafeldman** [comment]
Hey @odie2, I'm the lead developer of Freemius, the library that throws the notices. Few questions:
1. Is it still happening?
2. Are you running any cronjobs?
3. Would you be willing to let me debug the server?

**Comment by odie2** [comment]
Hi,

1. Yes - latest is `[23-Jan-2016 15:14:21 UTC]`. But let me update today the WP's version from 4.4 to 4.4.1.
2. Nope.
3. I can't, because it's public organisation's website.
However URL is http://zschocianow.pl/. I can debug (including modifying code) on my own for any action you wish.

**Comment by vovafeldman** [comment]
Modify line 178 in /aryo-activity-log/classes/freemius/includes/class-fs-api.php, change it to:
```php
$this->_logger->error( "Request:\n" . $method . ': ' . $path . "\nParams:\n" . var_export( $params, true ) . "\nResult:\n" . var_export( $result, true ) );
```

Let me know when it's changed in production.

**Comment by odie2** [comment]
@vovafeldman Modified.

Oh, I mistaked in last message, in point 1. Today is 24th January (facepalm). So the last time was at `[23-Jan-2016 21:25:29 UTC]`.

**Comment by vovafeldman** [comment]
If it happens again in the future, follow my suggestion and ping me so I can investigate.

**Comment by odie2** [comment]
@vovafeldman 

It happend yesterday again, but only for 161 line and headers:
`[24-Jan-2016 21:09:55 UTC] PHP Notice:  Trying to get property of non-object in /home/zschocianow/ftp/wordpress/wp-content/plugins/aryo-activity-log/classes/freemius/includes/class-fs-api.php on line 161`

Closest known and logged actions were: on `Sun, 24 Jan 2016 22:09:43 GMT` sign in of admin and custom call to `aal_insert_log()` on `Sun, 24 Jan 2016 22:10:40 GMT`.

WordPress was updated to version 4.4.1 on `Sun, 24 Jan 2016 16:05:09 GMT` (and that was previous action).

Possible actions like moving between admin pages by me (without changing anything) in period from where first error appear on `[24-Jan-2016 20:57:37 UTC]` until `[24-Jan-2016 21:09:55 UTC]`.

Headers errors (perhaps called by any visitor or me with admin privileges, without any change):
```[24-Jan-2016 21:03:22 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/zschocianow/ftp/wordpress/wp-content/plugins/aryo-activity-log/classes/freemius/includes/class-fs-api.php:161) in /home/zschocianow/ftp/wordpress/wp-content/themes/zschocianow/header.php on line 62

[24-Jan-2016 22:07:45 Europe/Warsaw] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/zschocianow/ftp/wordpress/wp-content/plugins/aryo-activity-log/classes/freemius/includes/class-fs-api.php:161) in /home/zschocianow/ftp/wordpress/wp-content/themes/zschocianow/page-templates/replacements.php on line 19```

I am sending you both files on Facebook to take a look into.

**Comment by vovafeldman** [comment]
Hey @odie2, it was too late when I checked it. Anyway, we release an update to the SDK that should fix the warnings and once the guys from Pojo (cc: @KingYes) will push an update to their plugin it should not happen again. BUT, if it does, please let me know.

**Comment by KingYes** [comment]
@odie2 Can I close this issue?

**Comment by odie2** [comment]
It seems like latest error was on `[27-Jan-2016 16:15:04 UTC]` - two days after I wrote, two days before vovafeldman wrote.

I just updated the plugin to 2.2.9 and if everything will be fine in 24 hours, I will close the issue.
